package io.roastedroot.inlay;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LockFileTest {

    @TempDir Path tempDir;

    @Test
    void writeAndReadRoundTrip() throws IOException {
        LockFile lockFile = new LockFile();
        lockFile.addOrUpdate(
                "ghcr.io/roastedroot/sqlite4j-wasm:3.51.0",
                "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890");
        lockFile.addOrUpdate(
                "ghcr.io/roastedroot/jq4j-wasm:1.7.1",
                "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef");

        Path lockPath = tempDir.resolve("wkg.lock");
        lockFile.write(lockPath);

        String content = Files.readString(lockPath);
        assertTrue(content.startsWith("# This file is automatically generated."));
        assertTrue(content.contains("[[packages]]"));

        LockFile loaded = LockFile.read(lockPath);
        assertEquals(2, loaded.getPackages().size());

        LockedPackage sqlite = loaded.findByImageRef("ghcr.io/roastedroot/sqlite4j-wasm:3.51.0");
        assertNotNull(sqlite);
        assertEquals("roastedroot:sqlite4j-wasm", sqlite.getName());
        assertEquals("ghcr.io", sqlite.getRegistry());
        assertEquals("3.51.0", sqlite.getVersion());
    }

    @Test
    void findByImageRefReturnsNullForUnknown() {
        LockFile lockFile = new LockFile();
        assertNull(lockFile.findByImageRef("ghcr.io/unknown/thing:v1"));
    }

    @Test
    void addOrUpdateReplacesExisting() {
        LockFile lockFile = new LockFile();
        lockFile.addOrUpdate("ghcr.io/org/foo:v1", "sha256:aaa");
        lockFile.addOrUpdate("ghcr.io/org/foo:v1", "sha256:bbb");
        assertEquals(1, lockFile.getPackages().size());
        assertEquals("sha256:bbb", lockFile.findByImageRef("ghcr.io/org/foo:v1").getDigest());
    }

    @Test
    void readNonExistentReturnsEmpty() throws IOException {
        LockFile loaded = LockFile.read(tempDir.resolve("nonexistent.lock"));
        assertNotNull(loaded);
        assertTrue(loaded.getPackages().isEmpty());
    }

    @Test
    void wkgCompatibleRead() throws IOException {
        Path lockPath = tempDir.resolve("wkg.lock");
        String wkgContent =
                "version = 1\n"
                    + "\n"
                    + "[[packages]]\n"
                    + "name = \"wasi:http\"\n"
                    + "registry = \"ghcr.io\"\n"
                    + "\n"
                    + "[[packages.versions]]\n"
                    + "requirement = \"=0.2.3\"\n"
                    + "version = \"0.2.3\"\n"
                    + "digest ="
                    + " \"sha256:deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef\"\n";
        Files.writeString(lockPath, wkgContent);

        LockFile loaded = LockFile.read(lockPath);
        assertEquals(1, loaded.getPackages().size());

        LockedPackage pkg = loaded.getPackages().get(0);
        assertEquals("wasi:http", pkg.getName());
        assertEquals("ghcr.io", pkg.getRegistry());
        assertEquals("0.2.3", pkg.getVersion());
    }

    @Test
    void malformedTomlThrows() throws IOException {
        Path lockPath = tempDir.resolve("wkg.lock");
        Files.writeString(lockPath, "this is [[[not valid toml");
        assertThrows(InlayException.class, () -> LockFile.read(lockPath));
    }

    @Test
    void emptyTomlReturnsEmptyList() throws IOException {
        Path lockPath = tempDir.resolve("wkg.lock");
        Files.writeString(lockPath, "version = 1\n");
        LockFile loaded = LockFile.read(lockPath);
        assertNotNull(loaded);
        assertTrue(loaded.getPackages().isEmpty());
    }

    @Test
    void resolveNamespaceBuiltinWasi() {
        String result = LockFile.resolveNamespace("", "wasi");
        assertEquals("wasi.dev", result);
    }

    @Test
    void resolveNamespaceUnknownReturnsNull() {
        String result = LockFile.resolveNamespace("", "unknown");
        assertNull(result);
    }
}
